### ISSUE TITLE
Hero shadow looks different in safari

### ISSUE THREAD

**Issue by rreeves8** [leoMirandaa/shadcn-landing-page#14]
<img width="1458" alt="Screenshot 2024-09-25 at 1 23 42 AM" src="https://github.com/user-attachments/assets/fc24d77e-f99a-4476-80a5-4f5d462b1eb5">

Missing cross browser support ?

**Comment by leoMirandaa** [comment]
Hello @rreeves8, you can add the prefix: -webkit- in the animations and keyframes.

Have a good day.

**Comment by rreeves8** [comment]
@leoMirandaa can you assist ? I can't figure out where to fix this

**Comment by leoMirandaa** [comment]
@rreeves8 Solved, contributor @jujoco helped us with this issue, please try it 👍
