### ISSUE TITLE
Please consider adding a LICENSE

### ISSUE THREAD

**Issue by TheBinaryGuy** [leoMirandaa/shadcn-landing-page#2]
Hi, this looks really good!

Is this an open source template? If so, then can you please add a compatible license?

Some more details on why open source projects should always have a license:
https://choosealicense.com/no-permission/

**Comment by tbscode** [comment]
Yes also saw this, really cool stuff would love to use It if it had a license :)

**Comment by leoMirandaa** [comment]
MIT license added

**Comment by leoMirandaa** [comment]
MIT license added

**Comment by TheBinaryGuy** [comment]
Thanks @leoMirandaa
