### ISSUE TITLE
Thoughts on `add` script?

### ISSUE THREAD

**Issue by mcavaliere** [leoMirandaa/shadcn-landing-page#9]
Great project!

Have you thought about adding a config file and script so that people can generate the landing page and only import the sections they want (just like Shadcn-ui itself)? I think this would be really useful for adding this landing page to an existing project, then customizing it with only the components the dev needs.

**Comment by leoMirandaa** [comment]
Thank you very much Mike 👍 I really appreciate it, I'm almost finishing Shadcn-Vue landing page template for Vue, I have some ideas in mind and one of them is the one you mention, It will be very helpful for the community.
